### ISSUE TITLE
Missing kuri_description package

### ISSUE THREAD

**Issue by dwhit** [KuriRobot/Kuri-Documentation#17]
Is there a way to get the kuri_description package so we can visualize the robot in RViz?

**Comment by po1** [comment]
there is a package called `gizmo_description` that should contain the robot description
it is embedded in the `edu` software tarball, accessible here: https://s3-us-west-1.amazonaws.com/freekuri-public-data/edu-develop-665bd82_amd64.tar.gz

Alternatively, your robot already comes with it. It is installed under `/opt/gizmo/share/gizmo_description`

**Comment by dwhit** [comment]
Great, I’ll download that tarball.
