### ISSUE TITLE
Using Kuri with Gazebo

### ISSUE THREAD

**Issue by nickswalker** [KuriRobot/Kuri-Documentation#24]
Are there any plans to distribute Kuri's simulation stack? We're offering Kuri as platform in [a robotics course](https://sites.google.com/view/cse481wi19/) so Gazebo support would help us a lot.

**Comment by po1** [comment]
I don't know if anyone from Bosch is watching this repository. You can find the URDF inside a Kuri, it's located in `/opt/gizmo/share/gizmo_description`. The URDF contains a reference to the `gazebo_ros_control` plugin, as you can see here:

```
    <gazebo>
      <plugin filename="libgazebo_ros_control.so" name="ros_control">
        <ns></ns>
        <robotSimType>gizmo_hw_sim/GizmoHwGazebo</robotSimType>
        <controlPeriod>0.001</controlPeriod>
      </plugin>
    </gazebo>
```

This will look for a pluginlib plugin called `gizmo_hw_sim/GizmoHwGazebo`. See this link for more details on how this works: http://gazebosim.org/tutorials/?tut=ros_control

You can find examples of how to implement your own simulation plugin for Kuri here (taken from the PAL Robotics open-source REEM simulation stack): https://github.com/pal-robotics/reem_simulation/tree/hydro-devel/reem_hardware_gazebo

**Comment by nickswalker** [comment]
I was able to hack together the necessary configuration here based on your advice: https://github.com/cse481wi19/cse481wi19/tree/indigo-devel/kuri_gazebo

Thank you for the pointers!

**Comment by po1** [comment]
thanks a lot for putting that together!
