### ISSUE TITLE
Documentation description does not match files on kuri

### ISSUE THREAD

**Issue by MahmoudNasr95** [KuriRobot/Kuri-Documentation#26]
The documentation provided does not reflect what is actually present on Kuri.
I am unable to access vision through any of the methods provided. Even the documentation or webrtc speaks of files that do not exist.
Is there any way I can get to the source code so I can use the robot for development?
All provided packages are already executables. I tried using kuri_edu package and it gives errors in running.

**Comment by po1** [comment]
@MahmoudNasr95 can you be more specific? Do you have an example of such files that you couldn't find?

I don't know of anybody with access to the source code at this point, all we can do is provide volunteer support based on the software you have on your robot.

**Comment by MahmoudNasr95** [comment]
For kuri_edu: I tried running the kuri_edu.launch file which is the first check mentioned in the kuri_edu documentation. That gives an error that the v4l2 buffers cannot be requested as the Device or resource is busy.

For webrtc: I can't find the following file as shown from the documentation:
![screenshot from 2019-02-04 14-18-51](https://user-images.githubusercontent.com/23210029/52231428-e9387c80-2887-11e9-8394-ce9fc8b2322c.png)
