### ISSUE TITLE
Adding custom voice command

### ISSUE THREAD

**Issue by FediHachicha** [KuriRobot/Kuri-Documentation#28]
Hi,
I tried adding a custom voice command within the "custom_commands.json" file. I also tried modifying one of the commands with adding a custom expression. Below the way I did it:
**{
    "Expression": "(([\"are\"] . \"you\" . (\"tired\" | \"sleepy\" | \"hungry\" | \"sick\")) | \"do you need to charge\")",
    "Result": {
      "name": "are you tired"
    },
    "SpokenResponse": "Let me check",
    "SpokenResponseLong": "Let me check",
    "WrittenResponse": "Let me check",
    "WrittenResponseLong": "Let me check",
    "TestPhrases": [
      {
        "Phrase": "are you sick",
        "ShouldMatch": true
      }
]**

I tried listening to the audio/voice_delegate/exchange topic and the message was transcribed properly but it doesn't correspond to the any trigger.

**commands: 
    name:
    params: []
error: 
transcription: are you sick**

Is this way correct to add custom voice commands to Kuri?

**Comment by KaijenHsiao** [comment]
I'm sorry, it turns out the mechanism that was created just before Mayfield shut down, to add custom voice commands... uses IFTTT.  And IFTTT removed Kuri, so it doesn't work anymore. :(
