### ISSUE TITLE
Wiping and restoring Kuri

### ISSUE THREAD

**Issue by nickswalker** [KuriRobot/Kuri-Documentation#29]
We'd like to try some destructive modifications to Kuri's default package set/system configuration. Is there an easy/recommended way to restore Kuri to factory configuration?

**Comment by po1** [comment]
There are some rough (but tested) steps here to reprovision a robot to the last software release: https://docs.google.com/document/d/1-yDORDclq-XxZuKzSzBqrcBa02XYEb7P2LkYXJ7W87A

Note: these steps will change the robot UUID and all crypto keys, wipe clean all data and configuration, including stored moments. The robot also won’t work with cloud services anymore until a cloud admin manually updates it.

**Comment by nickswalker** [comment]
Thank you!

**Comment by tgroechel** [comment]
Can confirm this still works/enables ssh, I'm having issues connecting to any servers/had to set up a new Kuri. Might help #37
