### ISSUE TITLE
Orange light doesn’t turn blue

### ISSUE THREAD

**Issue by zkytony** [KuriRobot/Kuri-Documentation#38]
When connecting Kuri to the charger, and pressing the power button, the power light shows orange. This isn’t documented I suppose? And the app doesn’t have instructions for this. What is going on in Kuri and how to fix it?

**Comment by Carter90** [comment]
As I recall Orange is before Kuri finished booting up. 
Have you tried switching the battery disconnect under Kuri, then power button to discharge the capacitors, waiting about 40 seconds, then switching the battery disconnect back on and try and power it up?

**Comment by zkytony** [comment]
I will give that a try. In case it doesn’t work is there any way to connect to the on-board computer to debug the issue?

**Comment by Carter90** [comment]
I think that there is an Ethernet port and USB inside but requires a very fairly thorough disassembly. I've always been curious but never wanting to risk it.

**Comment by Carter90** [comment]
Has your Kuri ever been set up on your network? If so you might see if she's booted up but ros has not started up and you could SSH in (I've had to do this a few times)

**Comment by Carter90** [comment]
Also if you do do the disassembly you can leave a short ethernet cord that you could pop off the little sidearms(flathead screwdriver) to be able to get access to in the future.

**Comment by zkytony** [comment]
Thanks! I believe our Kuri was once set up on our network but when we moved it to another building, the orange light issue started happening. I am extremely new to kuri. When kuri is not connected to a network, how to control it? Bluetooth via the app?

**Comment by zkytony** [comment]
Never mind it does turn on I pressed the wrong button. I pressed the +/- button instead of power button.

but now I can’t connect to it on the app

**Comment by nickswalker** [comment]
I think we stopped being able to connect to our Kuri's via the app sometime last year.

Getting a physical connection isn't too much hassle and is something that you're likely to need eventually anyways. The ethernet jack is taken up by the lidar, so it's preferable to either [make a debug cable](https://github.com/KuriRobot/Kuri-Documentation/blob/master/guides/hardware/debug-cable.md) or get a USB-serial chain and plug it into the free USB port. Both will work, though I did experience some issues with the camera not working when using the USB-serial solution.

**Comment by zkytony** [comment]
Got it. Thanks @nickswalker !

We actually do have ssh access, it’s just the app doesn’t work. Do you know if it’s possible to do things that you would do in the app through the ssh terminal? Like building a map, navigation, taking pictures? I would think so, but not sure how.

**Comment by nickswalker** [comment]
Yes, you can most anything once you figure out the right nodes to launch and how to use their interfaces. It's possible to use Mayfield's oort mapping (see their examples in the `kuri_edu` repo) or gmapping (as you would normally). You can use Mayfield's navigation stack as well (see `kuri_edu`), or move_base (again as usual). They have a unique interface for the camera, so you can see their docs on madmux for how to use that. Our repo has [some example usage](https://github.com/hcrlab/kuri/tree/melodic-devel/kuri_api/scripts) for photos/videos, as well as examples of most of the configuration and launch files that one would be interested for other capabilities as well.
