### ISSUE TITLE
Kuri Tread Product Information

### ISSUE THREAD

**Issue by amalnanavati** [KuriRobot/Kuri-Documentation#40]
Our Kuri's left tread has come off. We have had this Kuri for several years, so it could be routine wear-and-tear. Interestingly enough, the right tread is perfectly fine, but over the course of ~1 hour the left tread completely flaked off.

**I was wondering if you could share information about the manufacturer and part number for the tread, so we can order a replacement?** Thank you!

**Comment by amalnanavati** [comment]
These pictures show the tread as it was flaking (it has now completely flaked off).

![IMG_4253](https://user-images.githubusercontent.com/8277986/137777643-7d63d806-36ad-4d53-967c-ad9134bbd8fa.jpg)

![IMG_4254](https://user-images.githubusercontent.com/8277986/137777658-6aa8a9c6-136f-4fef-9f06-25fd6d8b4960.jpg)

**Comment by Carter90** [comment]
You might reach out to @MartinBodo in Santa Clara might have a spare one

**Comment by Carter90** [comment]
Sometimes the inside of a belt will have numbers you can look up.

**Comment by KaijenHsiao** [comment]
email me at kaijenhsiao@gmail.com and I can hook you up with a replacement.  The tank treads are custom.

**Comment by amalnanavati** [comment]
Got the replacement wheels, and it works. Thanks so much everyone!
